from copy import deepcopy
from typing import Any


DEMO_POLICYGRAPH_PAYLOAD: dict[str, Any] = {
    "policy": {
        "title": "Vacancy tax on idle private flats",
        "subtitle": "Release under-used homes without building new supply first.",
        "summary": (
            "A targeted annual tax on private flats left empty for more than 12 months, paired with "
            "vacancy-data matching and a temporary rental-placement channel for compliant owners."
        ),
        "question": "Can Hong Kong reduce rent pressure by moving idle private units back into use?",
        "intervention": {
            "title": "Verified vacancy tax + rental placement",
            "action": (
                "Match utility, rating, tenancy, and owner-declaration data; tax confirmed long-term "
                "vacancies; offer a six-month placement service before enforcement begins."
            ),
            "why": (
                "The map shows the root bottleneck is not tenant demand itself. It is the holding incentive "
                "that keeps usable flats empty while scarcity and prices rise."
            ),
            "leverage_node": "Landlord holding incentive",
        },
    },
    "stakeholders": [
        {
            "id": "housing-bureau",
            "name": "Housing Bureau",
            "role": "Sets policy design, exemptions, and public accountability.",
            "tone": "government",
            "x": 160,
            "y": 110,
        },
        {
            "id": "rating-valuation",
            "name": "Rating and Valuation Department",
            "role": "Runs vacancy verification and tax administration.",
            "tone": "government",
            "x": 460,
            "y": 72,
        },
        {
            "id": "private-landlords",
            "name": "Private landlords",
            "role": "Decide whether to keep flats empty, rent them, or sell.",
            "tone": "market",
            "x": 760,
            "y": 118,
        },
        {
            "id": "tenants",
            "name": "Renting households",
            "role": "Experience rent pressure and benefit from added supply.",
            "tone": "people",
            "x": 240,
            "y": 500,
        },
        {
            "id": "home-buyers",
            "name": "First-time buyers",
            "role": "Affected by sale prices, investor demand, and supply confidence.",
            "tone": "people",
            "x": 520,
            "y": 552,
        },
        {
            "id": "investors",
            "name": "Property investors",
            "role": "Respond to price expectations and holding costs.",
            "tone": "market",
            "x": 850,
            "y": 472,
        },
        {
            "id": "banks",
            "name": "Mortgage banks",
            "role": "Watch collateral values, borrower risk, and market liquidity.",
            "tone": "market",
            "x": 1030,
            "y": 300,
        },
        {
            "id": "district-councils",
            "name": "District councils",
            "role": "Surface local complaints and trust risks.",
            "tone": "people",
            "x": 90,
            "y": 315,
        },
    ],
    "nodes": [
        {
            "id": "political-pressure",
            "label": "Rent pressure complaints",
            "type": "Public signal",
            "description": "Visible pressure from renters and districts when rents rise faster than incomes.",
            "x": 88,
            "y": 355,
            "tone": "people",
        },
        {
            "id": "vacancy-tax",
            "label": "Vacancy tax enforcement",
            "type": "Policy lever",
            "description": "A verified charge on homes left idle after a grace period and exemption review.",
            "x": 238,
            "y": 205,
            "tone": "government",
        },
        {
            "id": "vacancy-data",
            "label": "Verified vacancy data",
            "type": "Evidence system",
            "description": "Matched utility, rating, tenancy, and owner-declaration records.",
            "x": 428,
            "y": 132,
            "tone": "government",
        },
        {
            "id": "owner-compliance",
            "label": "Owner compliance",
            "type": "Implementation behavior",
            "description": "Owners report status accurately and respond before enforcement escalates.",
            "x": 615,
            "y": 182,
            "tone": "market",
        },
        {
            "id": "holding-incentive",
            "label": "Landlord holding incentive",
            "type": "Root bottleneck",
            "description": "The payoff from keeping a unit empty while waiting for capital gains.",
            "x": 780,
            "y": 245,
            "tone": "market",
        },
        {
            "id": "idle-flats",
            "label": "Idle private flats",
            "type": "Housing stock",
            "description": "Usable homes kept off the rental or sale market.",
            "x": 650,
            "y": 355,
            "tone": "market",
        },
        {
            "id": "available-supply",
            "label": "Available rental supply",
            "type": "Market stock",
            "description": "Private homes actually available to households now.",
            "x": 455,
            "y": 415,
            "tone": "housing",
        },
        {
            "id": "rental-prices",
            "label": "Rental prices",
            "type": "Public outcome",
            "description": "Monthly housing cost faced by renting households.",
            "x": 252,
            "y": 500,
            "tone": "people",
        },
        {
            "id": "housing-scarcity",
            "label": "Perceived scarcity",
            "type": "Market signal",
            "description": "Belief that usable homes are hard to access, which affects prices and expectations.",
            "x": 525,
            "y": 572,
            "tone": "housing",
        },
        {
            "id": "property-prices",
            "label": "Property prices",
            "type": "Market outcome",
            "description": "Sale prices for private flats, including expectations of future gains.",
            "x": 760,
            "y": 570,
            "tone": "market",
        },
        {
            "id": "investor-demand",
            "label": "Investor demand",
            "type": "Market actor pressure",
            "description": "Purchasing interest from buyers seeking capital appreciation rather than occupancy.",
            "x": 960,
            "y": 475,
            "tone": "market",
        },
        {
            "id": "mortgage-risk",
            "label": "Mortgage risk monitoring",
            "type": "Financial constraint",
            "description": "Bank caution when prices move quickly or liquidity weakens.",
            "x": 1052,
            "y": 300,
            "tone": "finance",
        },
        {
            "id": "public-trust",
            "label": "Public trust",
            "type": "Legitimacy",
            "description": "Confidence that the tax is fair, evidence-based, and not a hidden broad property tax.",
            "x": 268,
            "y": 72,
            "tone": "government",
        },
    ],
    "edges": [
        {
            "source": "rental-prices",
            "target": "political-pressure",
            "polarity": "+",
            "label": "raises",
            "explanation": "Higher rents create complaints and pressure for government action.",
        },
        {
            "source": "political-pressure",
            "target": "vacancy-tax",
            "polarity": "+",
            "label": "activates",
            "explanation": "Visible rent pressure makes enforcement politically necessary.",
        },
        {
            "source": "vacancy-tax",
            "target": "holding-incentive",
            "polarity": "-",
            "label": "weakens",
            "explanation": "A verified tax reduces the payoff from holding a usable flat empty.",
        },
        {
            "source": "holding-incentive",
            "target": "idle-flats",
            "polarity": "+",
            "label": "increases",
            "explanation": "When holding is profitable, more units remain empty.",
        },
        {
            "source": "idle-flats",
            "target": "available-supply",
            "polarity": "-",
            "label": "removes",
            "explanation": "Idle flats are usable homes missing from the rental market.",
        },
        {
            "source": "available-supply",
            "target": "rental-prices",
            "polarity": "-",
            "label": "eases",
            "explanation": "More available rentals reduce scarcity pressure on rents.",
        },
        {
            "source": "available-supply",
            "target": "housing-scarcity",
            "polarity": "-",
            "label": "reduces",
            "explanation": "Visible supply lowers the perception that homes are inaccessible.",
        },
        {
            "source": "housing-scarcity",
            "target": "property-prices",
            "polarity": "+",
            "label": "pushes up",
            "explanation": "Scarcity expectations support higher sale prices.",
        },
        {
            "source": "property-prices",
            "target": "investor-demand",
            "polarity": "+",
            "label": "attracts",
            "explanation": "Rising prices attract investors seeking capital gains.",
        },
        {
            "source": "investor-demand",
            "target": "holding-incentive",
            "polarity": "+",
            "label": "reinforces",
            "explanation": "Investor appetite makes holding vacant units feel safer and more profitable.",
        },
        {
            "source": "property-prices",
            "target": "mortgage-risk",
            "polarity": "+",
            "label": "raises",
            "explanation": "Fast price growth increases bank concern about collateral and repayment risk.",
        },
        {
            "source": "mortgage-risk",
            "target": "investor-demand",
            "polarity": "-",
            "label": "restrains",
            "explanation": "Tighter lending reduces speculative purchasing capacity.",
        },
        {
            "source": "public-trust",
            "target": "owner-compliance",
            "polarity": "+",
            "label": "improves",
            "explanation": "Owners are more likely to comply when exemptions and data use feel fair.",
        },
        {
            "source": "owner-compliance",
            "target": "vacancy-data",
            "polarity": "+",
            "label": "improves",
            "explanation": "Accurate declarations improve the vacancy dataset.",
        },
        {
            "source": "vacancy-data",
            "target": "vacancy-tax",
            "polarity": "+",
            "label": "targets",
            "explanation": "Better data makes enforcement more precise and defensible.",
        },
        {
            "source": "vacancy-tax",
            "target": "public-trust",
            "polarity": "+",
            "label": "can build",
            "explanation": "Transparent enforcement can increase trust when residents see idle homes released.",
        },
    ],
    "loops": [
        {
            "id": "r1-speculative-holding",
            "label": "R1 Speculative holding",
            "type": "reinforcing",
            "nodes": ["property-prices", "investor-demand", "holding-incentive", "idle-flats", "available-supply", "housing-scarcity", "property-prices"],
            "summary": "Prices attract investors, investors strengthen holding incentives, idle homes reduce available supply, scarcity supports prices.",
            "intervention": "Break the loop at landlord holding incentive.",
        },
        {
            "id": "b1-release-supply",
            "label": "B1 Supply release",
            "type": "balancing",
            "nodes": ["rental-prices", "political-pressure", "vacancy-tax", "holding-incentive", "idle-flats", "available-supply", "rental-prices"],
            "summary": "Higher rents create political pressure, enforcement weakens vacancy incentives, released supply eases rents.",
            "intervention": "Make enforcement fast enough that supply reaches the market before rent pressure compounds.",
        },
        {
            "id": "r2-trust-compliance",
            "label": "R2 Trust and compliance",
            "type": "reinforcing",
            "nodes": ["public-trust", "owner-compliance", "vacancy-data", "vacancy-tax", "public-trust"],
            "summary": "Fair rules increase compliance, better data improves targeting, targeted enforcement builds legitimacy.",
            "intervention": "Publish exemption rules and a simple owner declaration route before penalties.",
        },
    ],
    "impact": {
        "baseline": [
            {"label": "Available rental supply", "value": 42},
            {"label": "Rent pressure", "value": 78},
            {"label": "Speculative vacancy", "value": 72},
            {"label": "Public trust", "value": 46},
            {"label": "Market stability", "value": 50},
        ],
        "after": [
            {"label": "Available rental supply", "value": 68},
            {"label": "Rent pressure", "value": 52},
            {"label": "Speculative vacancy", "value": 38},
            {"label": "Public trust", "value": 67},
            {"label": "Market stability", "value": 61},
        ],
    },
    "comparison": [
        {
            "label": "Weak policy",
            "title": "Temporary rent subsidy",
            "effect": "Helps tenants briefly, but leaves idle supply and holding incentives untouched.",
            "score": 43,
        },
        {
            "label": "Strong leverage",
            "title": "Verified vacancy tax",
            "effect": "Changes the root incentive, moves idle homes into use, and reduces pressure across loops.",
            "score": 82,
        },
    ],
}


def get_demo_policygraph_payload() -> dict[str, Any]:
    return deepcopy(DEMO_POLICYGRAPH_PAYLOAD)
