DEFAULT_SCENARIO = {
    "slug": "default-housing-pilot",
    "name": "Housing Policy Loop Navigator",
    "city_name": "Harborview",
    "summary": (
        "A systems-policy sandbox for city analysts to test housing interventions against "
        "stakeholder incentives, reinforcing loops, and neighborhood stress."
    ),
    "analyst_prompt": (
        "Choose a housing policy, stress-test the loops it touches, then compare intervention "
        "points before drafting the final brief."
    ),
    "baseline_metrics": [
        {
            "slug": "housing_affordability",
            "label": "Housing affordability",
            "value": 42,
            "unit": "/100",
            "explanation": "Affordability is low because supply delivery lags rent pressure in growth zones.",
        },
        {
            "slug": "permitting_speed",
            "label": "Permitting speed",
            "value": 38,
            "unit": "/100",
            "explanation": "Manual review and fragmented approvals slow projects even when policy intent is clear.",
        },
        {
            "slug": "rental_stability",
            "label": "Rental stability",
            "value": 47,
            "unit": "/100",
            "explanation": "Tenants face churn in transit-rich neighborhoods where new demand is strongest.",
        },
        {
            "slug": "public_trust",
            "label": "Public trust",
            "value": 44,
            "unit": "/100",
            "explanation": "Communities are skeptical because delivery promises and infrastructure sequencing rarely stay aligned.",
        },
        {
            "slug": "delivery_capacity",
            "label": "Delivery capacity",
            "value": 51,
            "unit": "/100",
            "explanation": "The city can build, but approvals and utility readiness throttle throughput.",
        },
        {
            "slug": "infrastructure_readiness",
            "label": "Infrastructure readiness",
            "value": 46,
            "unit": "/100",
            "explanation": "Transit, schools, and utilities are unevenly prepared for concentrated density surges.",
        },
    ],
    "stakeholders": [
        {
            "slug": "housing-department",
            "name": "Housing Delivery Office",
            "motivation": "Increase production and keep mixed-income commitments credible.",
            "influence_level": 88,
            "role_description": "Owns delivery targets and negotiates policy tradeoffs across agencies.",
        },
        {
            "slug": "planning-commission",
            "name": "Planning Commission",
            "motivation": "Protect process legitimacy while managing land-use change.",
            "influence_level": 82,
            "role_description": "Controls entitlements, reviews, and how quickly new density rules move.",
        },
        {
            "slug": "developer-coalition",
            "name": "Developer Coalition",
            "motivation": "Pursue viable projects with predictable approvals and infrastructure support.",
            "influence_level": 76,
            "role_description": "Responds quickly to permitting friction and financing uncertainty.",
        },
        {
            "slug": "tenant-union",
            "name": "Tenant Union Network",
            "motivation": "Reduce displacement risk and protect residents during transition.",
            "influence_level": 72,
            "role_description": "Shapes political trust and neighborhood acceptance of new policy.",
        },
        {
            "slug": "transit-agency",
            "name": "Transit & Utilities Agency",
            "motivation": "Sequence growth with service capacity and avoid overloaded corridors.",
            "influence_level": 68,
            "role_description": "Acts as a gating stakeholder whenever density rises faster than infrastructure upgrades.",
        },
    ],
    "system_nodes": [
        {
            "slug": "housing-department",
            "name": "Housing Delivery Office",
            "node_type": "stakeholder",
            "description": "Owns housing targets and coordinates executive delivery pressure.",
            "influence_score": 88,
            "x": 12,
            "y": 16,
            "stakeholder_slug": "housing-department",
        },
        {
            "slug": "planning-commission",
            "name": "Planning Commission",
            "node_type": "stakeholder",
            "description": "Controls the tempo and credibility of approvals.",
            "influence_score": 82,
            "x": 36,
            "y": 12,
            "stakeholder_slug": "planning-commission",
        },
        {
            "slug": "developer-coalition",
            "name": "Developer Coalition",
            "node_type": "stakeholder",
            "description": "Invests when entitlement risk and timelines look manageable.",
            "influence_score": 76,
            "x": 69,
            "y": 18,
            "stakeholder_slug": "developer-coalition",
        },
        {
            "slug": "tenant-union",
            "name": "Tenant Union Network",
            "node_type": "stakeholder",
            "description": "Raises community warnings when displacement signals spike.",
            "influence_score": 72,
            "x": 14,
            "y": 56,
            "stakeholder_slug": "tenant-union",
        },
        {
            "slug": "transit-agency",
            "name": "Transit & Utilities Agency",
            "node_type": "stakeholder",
            "description": "Can accelerate or bottleneck projects through service readiness.",
            "influence_score": 68,
            "x": 72,
            "y": 58,
            "stakeholder_slug": "transit-agency",
        },
        {
            "slug": "permitting-speed",
            "name": "Permitting Speed",
            "node_type": "factor",
            "description": "How quickly viable housing projects move from review to shovel-ready status.",
            "influence_score": 84,
            "x": 48,
            "y": 30,
            "stakeholder_slug": None,
        },
        {
            "slug": "housing-supply",
            "name": "Housing Supply",
            "node_type": "factor",
            "description": "Net pipeline of new homes coming online in the next 24 months.",
            "influence_score": 91,
            "x": 55,
            "y": 46,
            "stakeholder_slug": None,
        },
        {
            "slug": "rent-pressure",
            "name": "Rent Pressure",
            "node_type": "factor",
            "description": "Market pressure on households in high-demand neighborhoods.",
            "influence_score": 86,
            "x": 34,
            "y": 50,
            "stakeholder_slug": None,
        },
        {
            "slug": "public-trust",
            "name": "Public Trust",
            "node_type": "factor",
            "description": "Whether residents believe promised housing benefits will actually arrive.",
            "influence_score": 79,
            "x": 30,
            "y": 72,
            "stakeholder_slug": None,
        },
        {
            "slug": "infrastructure-capacity",
            "name": "Infrastructure Capacity",
            "node_type": "factor",
            "description": "Transit, utilities, and public-service headroom in growth areas.",
            "influence_score": 75,
            "x": 63,
            "y": 74,
            "stakeholder_slug": None,
        },
        {
            "slug": "inclusionary-rezoning",
            "name": "Inclusionary Rezoning Surge",
            "node_type": "policy",
            "description": "Upzones transit corridors with mixed-income requirements.",
            "influence_score": 74,
            "x": 84,
            "y": 38,
            "stakeholder_slug": None,
        },
        {
            "slug": "permit-digital-twin",
            "name": "Permit Digital Twin",
            "node_type": "policy",
            "description": "Digitizes approvals and exposes real-time process bottlenecks.",
            "influence_score": 70,
            "x": 83,
            "y": 11,
            "stakeholder_slug": None,
        },
        {
            "slug": "community-land-trust-bundle",
            "name": "Community Land Trust Bundle",
            "node_type": "policy",
            "description": "Pairs land banking, tenant protections, and mission-driven housing delivery.",
            "influence_score": 72,
            "x": 83,
            "y": 66,
            "stakeholder_slug": None,
        },
    ],
    "system_edges": [
        {
            "source": "planning-commission",
            "target": "permitting-speed",
            "label": "sets review tempo",
            "polarity": 1,
            "strength": 9,
            "explanation": "Planning review discipline is the immediate throttle on project movement.",
        },
        {
            "source": "permitting-speed",
            "target": "housing-supply",
            "label": "unlocks completions",
            "polarity": 1,
            "strength": 10,
            "explanation": "Faster approvals convert latent projects into delivered homes.",
        },
        {
            "source": "housing-supply",
            "target": "rent-pressure",
            "label": "absorbs pressure",
            "polarity": -1,
            "strength": 9,
            "explanation": "When supply rises, rent pressure and bidding wars ease.",
        },
        {
            "source": "rent-pressure",
            "target": "tenant-union",
            "label": "activates resistance",
            "polarity": 1,
            "strength": 8,
            "explanation": "Higher rent stress triggers stronger tenant organizing and caution demands.",
        },
        {
            "source": "tenant-union",
            "target": "public-trust",
            "label": "signals legitimacy risk",
            "polarity": -1,
            "strength": 7,
            "explanation": "Visible tenant alarm lowers confidence that growth will be inclusive.",
        },
        {
            "source": "public-trust",
            "target": "planning-commission",
            "label": "shapes review friction",
            "polarity": -1,
            "strength": 8,
            "explanation": "Lower public trust raises the political cost of moving quickly.",
        },
        {
            "source": "transit-agency",
            "target": "infrastructure-capacity",
            "label": "gates readiness",
            "polarity": 1,
            "strength": 8,
            "explanation": "Agency sequencing determines whether density hits prepared corridors.",
        },
        {
            "source": "infrastructure-capacity",
            "target": "public-trust",
            "label": "supports confidence",
            "polarity": 1,
            "strength": 6,
            "explanation": "Residents trust housing plans more when services arrive with growth.",
        },
        {
            "source": "inclusionary-rezoning",
            "target": "housing-supply",
            "label": "expands capacity",
            "polarity": 1,
            "strength": 8,
            "explanation": "Rezoning creates room for more homes, especially near transit.",
        },
        {
            "source": "inclusionary-rezoning",
            "target": "infrastructure-capacity",
            "label": "stresses sequencing",
            "polarity": -1,
            "strength": 6,
            "explanation": "Density surges can outpace utilities and schools without phasing.",
        },
        {
            "source": "permit-digital-twin",
            "target": "permitting-speed",
            "label": "removes delay",
            "polarity": 1,
            "strength": 9,
            "explanation": "Shared workflow data trims review loops and exposes bottlenecks.",
        },
        {
            "source": "community-land-trust-bundle",
            "target": "public-trust",
            "label": "builds social license",
            "polarity": 1,
            "strength": 8,
            "explanation": "Visible anti-displacement protections make growth easier to defend.",
        },
    ],
    "loops": [
        {
            "slug": "approval-bottleneck",
            "name": "Approval Bottleneck Loop",
            "loop_type": "reinforcing",
            "base_risk": 76,
            "explanation": (
                "When public trust drops, review friction rises, permitting slows, supply stalls, "
                "and scarcity makes future approvals even harder."
            ),
            "intervention_signal": "Process fixes must land before or alongside any growth surge.",
            "involved_nodes": [
                "planning-commission",
                "permitting-speed",
                "housing-supply",
                "public-trust",
            ],
        },
        {
            "slug": "displacement-anxiety",
            "name": "Displacement Anxiety Loop",
            "loop_type": "reinforcing",
            "base_risk": 71,
            "explanation": (
                "Rent pressure fuels resident fear, which lowers trust and strengthens resistance, "
                "slowing the very policy meant to relieve scarcity."
            ),
            "intervention_signal": "Tenant protection and benefit visibility must be coupled to growth policy.",
            "involved_nodes": [
                "rent-pressure",
                "tenant-union",
                "public-trust",
                "housing-department",
            ],
        },
        {
            "slug": "infrastructure-mismatch",
            "name": "Infrastructure Mismatch Loop",
            "loop_type": "reinforcing",
            "base_risk": 64,
            "explanation": (
                "If density outpaces utility and transit upgrades, service strain triggers political "
                "pushback and future approvals become more defensive."
            ),
            "intervention_signal": "Phase delivery and visible service upgrades to maintain trust.",
            "involved_nodes": [
                "transit-agency",
                "infrastructure-capacity",
                "public-trust",
                "inclusionary-rezoning",
            ],
        },
    ],
    "neighborhoods": [
        {
            "slug": "central-core",
            "name": "Central Core",
            "focus": "Transit-rich downtown where entitlement backlog is most visible.",
            "risk_level": 78,
            "x": 16,
            "y": 16,
            "width": 30,
            "height": 26,
            "accent": "#ff7a59",
            "explanation": "Fastest delivery upside, but the highest infrastructure stress if density moves alone.",
        },
        {
            "slug": "riverside",
            "name": "Riverside",
            "focus": "Mixed-income river corridor facing the sharpest displacement concerns.",
            "risk_level": 69,
            "x": 52,
            "y": 28,
            "width": 30,
            "height": 22,
            "accent": "#ffb347",
            "explanation": "Residents support new homes only when protection and benefit-sharing are explicit.",
        },
        {
            "slug": "north-gateway",
            "name": "North Gateway",
            "focus": "Expansion zone with land capacity but weaker service readiness.",
            "risk_level": 58,
            "x": 30,
            "y": 58,
            "width": 34,
            "height": 20,
            "accent": "#3dd6b5",
            "explanation": "Suitable for phased growth if utility upgrades are synchronized early.",
        },
    ],
    "policies": [
        {
            "slug": "inclusionary-rezoning",
            "name": "Inclusionary Rezoning Surge",
            "summary": "Unlock mixed-income housing around transit corridors.",
            "description": (
                "Expands zoning envelopes near stations while requiring mixed-income delivery. "
                "High upside on supply, but infrastructure and trust can break if sequencing lags."
            ),
            "default_intensity": 68,
            "policy_type": "land-use",
            "priority_hint": "affordability",
            "neighborhood_ids": ["central-core", "riverside"],
            "effect_profile": {
                "metric_deltas": {
                    "housing_affordability": 16,
                    "permitting_speed": -4,
                    "rental_stability": 9,
                    "public_trust": -3,
                    "delivery_capacity": 7,
                    "infrastructure_readiness": -8,
                },
                "loop_effects": {
                    "approval-bottleneck": -8,
                    "displacement-anxiety": -6,
                    "infrastructure-mismatch": 12,
                },
                "node_impacts": [
                    {
                        "node_slug": "housing-supply",
                        "impact": 18,
                        "rationale": "More zoned capacity increases the near-term project pipeline.",
                    },
                    {
                        "node_slug": "planning-commission",
                        "impact": 10,
                        "rationale": "Initial review complexity rises before streamlined patterns emerge.",
                    },
                    {
                        "node_slug": "infrastructure-capacity",
                        "impact": -12,
                        "rationale": "Transit-rich corridors absorb the earliest strain if upgrades lag.",
                    },
                ],
                "neighborhood_effects": {
                    "central-core": 14,
                    "riverside": 10,
                    "north-gateway": 5,
                },
            },
        },
        {
            "slug": "permit-digital-twin",
            "name": "Permit Digital Twin",
            "summary": "Expose approval bottlenecks and cut permitting delay.",
            "description": (
                "Creates a shared permitting workflow, exception tracking, and service-level dashboard "
                "across planning, housing, and infrastructure teams."
            ),
            "default_intensity": 74,
            "policy_type": "process",
            "priority_hint": "speed",
            "neighborhood_ids": ["central-core", "north-gateway"],
            "effect_profile": {
                "metric_deltas": {
                    "housing_affordability": 7,
                    "permitting_speed": 18,
                    "rental_stability": 3,
                    "public_trust": 5,
                    "delivery_capacity": 12,
                    "infrastructure_readiness": 4,
                },
                "loop_effects": {
                    "approval-bottleneck": -18,
                    "displacement-anxiety": -2,
                    "infrastructure-mismatch": -4,
                },
                "node_impacts": [
                    {
                        "node_slug": "permitting-speed",
                        "impact": 20,
                        "rationale": "Digital visibility removes repeat review loops and manual handoffs.",
                    },
                    {
                        "node_slug": "planning-commission",
                        "impact": 8,
                        "rationale": "Review teams can clear routine cases faster once shared data exists.",
                    },
                    {
                        "node_slug": "developer-coalition",
                        "impact": 11,
                        "rationale": "Predictable timelines make more projects financially viable.",
                    },
                ],
                "neighborhood_effects": {
                    "central-core": 8,
                    "riverside": 4,
                    "north-gateway": 9,
                },
            },
        },
        {
            "slug": "community-land-trust-bundle",
            "name": "Community Land Trust Bundle",
            "summary": "Pair land banking with tenant safeguards and mission-driven housing.",
            "description": (
                "Combines public land banking, right-to-return commitments, and targeted tenant support "
                "to keep trust intact while new supply arrives."
            ),
            "default_intensity": 62,
            "policy_type": "stability",
            "priority_hint": "stability",
            "neighborhood_ids": ["riverside", "north-gateway"],
            "effect_profile": {
                "metric_deltas": {
                    "housing_affordability": 11,
                    "permitting_speed": -2,
                    "rental_stability": 16,
                    "public_trust": 14,
                    "delivery_capacity": 4,
                    "infrastructure_readiness": 2,
                },
                "loop_effects": {
                    "approval-bottleneck": -4,
                    "displacement-anxiety": -16,
                    "infrastructure-mismatch": -2,
                },
                "node_impacts": [
                    {
                        "node_slug": "tenant-union",
                        "impact": 16,
                        "rationale": "Visible protections turn opposition into conditional support.",
                    },
                    {
                        "node_slug": "public-trust",
                        "impact": 15,
                        "rationale": "Residents see direct safeguards instead of abstract promises.",
                    },
                    {
                        "node_slug": "housing-department",
                        "impact": 9,
                        "rationale": "The city gains a clearer social license to sequence growth.",
                    },
                ],
                "neighborhood_effects": {
                    "central-core": 4,
                    "riverside": 13,
                    "north-gateway": 7,
                },
            },
        },
    ],
    "interventions": [
        {
            "slug": "phase-infrastructure-compact",
            "title": "Phase infrastructure compact",
            "summary": "Tie each rezoning wave to a visible utilities and service upgrade package.",
            "target_policy_slugs": ["inclusionary-rezoning"],
            "targeted_loop_slugs": ["infrastructure-mismatch"],
            "base_effectiveness": 88,
            "explanation": (
                "This intervention lowers the odds that density gains are politically reversed by "
                "service strain in the Central Core and Riverside corridors."
            ),
            "tradeoffs": [
                "Immediate unit release slows while phase gates are negotiated.",
                "Requires capital coordination across transit, schools, and utilities.",
            ],
            "metric_shifts": {
                "infrastructure_readiness": 10,
                "public_trust": 6,
                "delivery_capacity": -2,
            },
            "affected_nodes": ["transit-agency", "infrastructure-capacity", "public-trust"],
            "neighborhood_ids": ["central-core", "riverside"],
        },
        {
            "slug": "permit-concierge-lane",
            "title": "Mixed-income permit concierge lane",
            "summary": "Create a fast lane for projects that meet affordability and readiness thresholds.",
            "target_policy_slugs": ["inclusionary-rezoning", "permit-digital-twin"],
            "targeted_loop_slugs": ["approval-bottleneck"],
            "base_effectiveness": 84,
            "explanation": (
                "This clears the approval bottleneck without abandoning public accountability, "
                "especially for projects that already satisfy affordability commitments."
            ),
            "tradeoffs": [
                "Projects outside the fast lane may perceive unfair treatment.",
                "Staff capacity must be ring-fenced to keep the lane credible.",
            ],
            "metric_shifts": {
                "permitting_speed": 11,
                "delivery_capacity": 7,
                "public_trust": 3,
            },
            "affected_nodes": ["planning-commission", "permitting-speed", "developer-coalition"],
            "neighborhood_ids": ["central-core", "north-gateway"],
        },
        {
            "slug": "anti-displacement-benefit-pact",
            "title": "Anti-displacement benefit pact",
            "summary": "Publish tenant protections, relocation support, and right-to-return triggers up front.",
            "target_policy_slugs": ["inclusionary-rezoning", "community-land-trust-bundle"],
            "targeted_loop_slugs": ["displacement-anxiety"],
            "base_effectiveness": 86,
            "explanation": (
                "This directly reduces the displacement loop by giving residents visible guarantees "
                "before market pressure spikes."
            ),
            "tradeoffs": [
                "Program administration cost rises immediately.",
                "If enforcement is weak, trust can fall harder than before.",
            ],
            "metric_shifts": {
                "rental_stability": 9,
                "public_trust": 8,
                "housing_affordability": 3,
            },
            "affected_nodes": ["tenant-union", "public-trust", "rent-pressure"],
            "neighborhood_ids": ["riverside", "north-gateway"],
        },
        {
            "slug": "public-delivery-scoreboard",
            "title": "Public delivery scoreboard",
            "summary": "Expose policy promises, milestone progress, and neighborhood service readiness in one place.",
            "target_policy_slugs": ["permit-digital-twin", "community-land-trust-bundle"],
            "targeted_loop_slugs": ["approval-bottleneck", "displacement-anxiety"],
            "base_effectiveness": 78,
            "explanation": (
                "A public scoreboard turns policy into a trackable delivery contract and stabilizes trust "
                "when multiple agencies are involved."
            ),
            "tradeoffs": [
                "Operational failures become more visible to political leadership.",
                "Requires disciplined data governance across agencies.",
            ],
            "metric_shifts": {
                "public_trust": 10,
                "permitting_speed": 2,
                "delivery_capacity": 3,
            },
            "affected_nodes": ["housing-department", "public-trust", "planning-commission"],
            "neighborhood_ids": ["central-core", "riverside", "north-gateway"],
        },
    ],
}
